name: moneymove
description: gateway to gateway money transfer app

publish_to: 'none'

version: 1.2.1+4

environment:
  sdk: '>=3.6.0 <4.2.0'
  flutter: '3.27.1'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  country_code_picker: ^3.0.0
  material_design_icons_flutter: ^7.0.7296
  get_storage: ^2.1.1
  logger: 2.0.2+1
  pin_code_fields: ^8.0.1
  intl: ^0.18.0
  image_picker: ^1.1.2
  flutter_inappwebview: 5.8.0
  dotted_line: ^3.2.3
  flutter_svg:
  flutter_animate: ^4.5.0
  flutter_staggered_animations: ^1.1.1
  easy_stepper: ^0.8.5
  r_dotted_line_border: ^0.1.1
  dropdown_button2: ^2.3.9
  flutter_swiper_view: ^1.1.8
  flutter_card_swiper: ^7.0.2
  connectivity_plus: ^2.3.8
  flutter_spinkit: ^5.2.1
  loading_animation_widget: ^1.3.0
  local_auth: ^2.3.0
  permission_handler: ^11.3.1
  flutter_html:
  restart_app: ^1.3.2
  

# dependency_overrides:
#   modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  # flutter_app_name: ^0.1.0
  change_app_package_name: ^1.1.0
  build_runner:
  flutter_gen_runner:
  rename_app: ^1.6.1



flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo/app_launcher.png"

flutter_gen:
  output: lib/custom_assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
#  flutter packages pub run build_runner build
#  fluttergen -c pubspec.yaml  # only for mac

# project config command line
#  flutter pub run flutter_app_name && flutter pub run flutter_launcher_icons:main && flutter pub run change_app_package_name:main net.appdevs.adwallet
# ------------------- or ----------------
#  flutter pub run flutter_app_name
# flutter pub run flutter_launcher_icons:main
# flutter pub run change_app_package_name:main com.domain.appname


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/clipart/
    - assets/icon/
    - assets/logo/


